### ISSUE TITLE
Help: communikation example

### ISSUE THREAD

**Issue by nellydocs** [Xinyuan-LilyGO/T-Encoder-shield#2]
Hi,
could someone provide/link a communikation example between the shield and the T-Encoder.

**Comment by LilyGO** [comment]
I will upload a simple communication example for your reference later.

**Comment by LilyGO** [comment]
You can use UART to communicate with T-Encoder.

**Comment by johannesz-codes** [comment]
Could you provide an example for configuring UART?

**Comment by LilyGO** [comment]
I will upload an example later

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/T-Encoder-shield/tree/main/example/Arduino/T-Encoder%20linkage

**Comment by nellydocs** [comment]
Thanks Alot!!
