### ISSUE TITLE
Powering T-Encoder through T-Encoder-shield

### ISSUE THREAD

**Issue by jeff-phil** [Xinyuan-LilyGO/T-Encoder-shield#7]
Hi @LilyGO -

How do you power the T-Encoder through the T-Encoder-shield VBus?  

I get 3V from the VBus here:

<img width="438" alt="image" src="https://github.com/user-attachments/assets/d26acc33-6b9e-4d3c-b973-d09839aa054b">

But low amps, which is not enough to run T-Encoder from the shield.

**Comment by jeff-phil** [comment]
I guess more yes/no question that should be quick and easy to answer: Can T-Encoder-Shield directly power the T-Encoder without USB connected into T-Encoder?

我想知道，T-Encoder-Shield 能否直接给 T-Encoder 供电，而不需要插上 USB 线？

**Comment by jeff-phil** [comment]
No response here from LilyGO...🤔

I ended up solving myself by reversing D4 Schottky rectifier (SS34) orientation via re-solder.  DISCLAIMER: I would not recommend others do this, unless you know what you are doing, since this diode provides reverse and overflow protection when both T-Encoder and T-Encoder-shield are directly plugged-in via USB.  In reverse, now T-Encoder-shield can power the T-Encoder, and T-Encoder can no longer power the T-Encoder-shield.

**Comment by lewisxhe** [comment]
Hi @jeff-phil 

This diode is not necessary, you can just connect it directly. With this diode, only the USB-C of T-Encoder can power T-Encoder-shield. Short-circuiting this diode can power from micro-usb.
